[project]
name = "ipbd-casemethod-crypto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.42.96",
    "cryptography>=47.0.0",
    "loguru>=0.7.3",
    "pandas>=3.0.2",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "sqlalchemy>=2.0.49",
]

[tool.uv.workspace]
members = [
    "ipbd-casemethod",
]
